<?php

function _lrnapp_gitbook_books_callback($machine_name, $app_route) {
  $return = array();
  // load all gitbook nodes
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'git_book')
    ->propertyCondition('status', NODE_PUBLISHED);
  $result = $query->execute();
  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $nodes = entity_load('node', $nids);
    // for each gitbook load the repo and get the status
    foreach ($nodes as $node) {
      $repo = _git_book_get_repo($node);
      if ($repo) {
        $repo_status = _git_book_get_status($repo);
        // add the status to the returned data
        $return[] = array(
          'title' => $node->title,
          'nid' => $node->nid,
          'status' => $repo_status,
        );
      }
    }
  } 
  return array(
    'status' => '200',
    'data' => $return
  );
}

function _lrnapp_gitbook_canmerge_callback($machine_name, $app_route) {
  $return = array();
  return array(
    'status' => '200',
    'data' => $return
  );
}

function _lrnapp_gitbook_sync_callback($machine_name, $app_route) {
  $return = array();
  return array(
    'status' => '200',
    'data' => $return
  );
}

function _lrnapp_gitbook_commits_callback($machine_name, $app_route) {
  $return = array();
  return array(
    'status' => '200',
    'data' => $return
  );
}