version: "3"

services:
  devmachine:
    build:
      context: ./tools
      dockerfile: Dockerfile-devmachine
    entrypoint: /bin/bash
    volumes:
      - './core:/home/node/html/core'

  vagrant-sync:
    build:
      context: ./tools/vagrant-sync
      dockerfile: Dockerfile-vagrant-sync
    volumes:
      - "./core:/data"
      - "./vagrant/default/virtualbox/private_key:/root/.ssh/private_key"
    environment:
      - DESTINATION_HOST=vagrant@10.0.18.55
      - DESTINATION_DIR=/home/vagrant/elmsln/core
  
  vuejs:
    build:
      context: ./tools
      dockerfile: Dockerfile-devmachine
    volumes:
      - "./core:/home/node/html/core"

  generator-elmsln-cli:
    build:
      context: ./tools
      dockerfile: Dockerfile-devmachine
    entrypoint: yo elmsln-cli
    volumes:
      - '/home/node/html/tools/generator-elmsln-cli/node_modules'
      - './tools/generator-elmsln-cli:/home/node/html/tools/generator-elmsln-cli'
      - './core:/home/node/html/core'