version: "3"

services:
  devmachine:
    build:
      context: ./tools
      dockerfile: Dockerfile-devmachine
    entrypoint: /bin/bash
    volumes:
      - './core:/home/node/html/core'
      - './tools:/home/node/html/tools'